# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value


services:
    app.form.registration:
        class: UserBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    login_listener:
        class:  ContribuxBundle\Listeners\LoginListener
        arguments:
            userManager: "@fos_user.user_manager"
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    logout_handler:
            class: ContribuxBundle\Handler\LogoutHandler
            arguments:
                session: "@session"